env:
  DOCKER_COMPOSE_VERSION: 1.23.2
  CAOM2_SEARCH_SERVER_VERSION: 2.7.12
  CAOM2_META_UI_VERSION: 1013
language: java
group: edge
jdk:
- oraclejdk8
dist: trusty
sudo: required
services:
- docker
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose && sudo mv docker-compose /usr/local/bin
- docker-compose -v
- gradle -v
script:
- cd caom2-ui-server && gradle clean build javadoc install && cd ..
- cd caom2-meta-ui && gradle clean build
- mkdir docker && cp Dockerfile docker/ && cp build/libs/*.war docker/ 
- docker build -t opencadc/caom2-meta-ui:SNAPSHOT -t opencadc/caom2-meta-ui:alpine -t opencadc/caom2-meta-ui:${CAOM2_META_UI_VERSION} -f docker/Dockerfile docker/
- cd ../caom2-search-lib && gradle clean build javadoc install
- cd ../caom2-search-server && gradle clean build install
- cd examples/default
- gradle -i clean build
- mkdir docker && cp Dockerfile docker/ && cp build/libs/*.war docker/ && cp *.properties docker/
- docker build -t opencadc/caom2-search:SNAPSHOT -t opencadc/caom2-search:alpine -t opencadc/caom2-search:${CAOM2_SEARCH_SERVER_VERSION} -f docker/Dockerfile docker/
- cd ../int-test
- docker-compose up -d
- docker ps -a
- cd ../default
- gradle -i -PintTest_selenium_server_url=http://localhost:4444 -PintTest_web_app_url=http://proxy.cadc.dao.nrc.ca -PintTest_web_app_endpoint=/search/ intTestFirefox
after_success:
- cd $TRAVIS_BUILD_DIR
- if [ "$(. ./can-deploy.sh)" = "DEPLOY" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push opencadc/caom2-search:$CAOM2_SEARCH_SERVER_VERSION; docker push opencadc/caom2-search:alpine; docker push opencadc/caom2-meta-ui:$CAOM2_META_UI_VERSION; docker push opencadc/caom2-meta-ui:alpine fi
- if [ "$(. ./can-deploy.sh)" != "DEPLOY" ]; then echo "Not deploying."; fi
notifications:
  slack:
    secure: WwH5T9fWOsWT5/sqS0t5vifKTGQbzHdSGo0DWt1YnfjFLC2NRWMiQ43TD3G+eGtoNaQ/4qcesiGG8ooJMjUjugf5GqQCKohuSfGWl3Tq44UOJD3MDFBe34YINPSe2fNAz3gO9jDKdJHTCilnyWg6bNO7LHSynt7kjDSDi/i04q3OSrV989niHu5yvDSLz2K/ydDRUFzjnQLlAcRNC3M1WGXoOiAIyGqxSbIBF9GXmOi3XB5HvH3Bvi4+wTkoxknRtSlnUZOBtC6iYTUZ7nubLItoA59o/LQ9bmHxcxWlfylRbhieKc4rCFflNKx/YaKrLLYFKlGlshr9Nf+R4OeI4SAPS4rvZbx4afXnJZrM7qleksU6yCON7RHz/546saYC4HGV6HZ/maNczJ7QsaK/5M6CUx4NsVVAKNmIhRZl12/sZEafrm5POQM3jg+560YorTk9H0NfAXraC7J8Lb0/oBkVb7qMj+0awc4n8xO5uU390OjgAl4G7oSR/PBeoC19OZA7pWH4u6I5eoUcv6CUyFQ6OnNqSJsKNQr7Nd3IOblhUmTV6oFBvTIFuOSChp1UdMPLK9numcje7dnGD3xw4BkKTdiUgD3/3G8oJY8W5GrV9MYe4WBnlJoReq82JfwJN63DHQ8HKlwzMgE+UrKNEbznPVENUslMuHK16YtbZ9w=
