version: '3.2'
services:
  proxy.cadc.dao.nrc.ca:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - 'caom2metaui'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - './root:/usr/share/nginx/html'
    depends_on:
      - caom2-meta-ui.cadc.dao.nrc.ca
  caom2-meta-ui.cadc.dao.nrc.ca:
    image: opencadc/caom2-meta-ui:SNAPSHOT
    networks:
      - 'caom2metaui'
    environment:
      CATALINA_OPTS: -Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca

# Create the network for which this system will run within.
networks:
  caom2metaui:
