env:
  DOCKER_COMPOSE_VERSION: 1.23.2
  REGISTRY_HOST: proxy.cadc.dao.nrc.ca
  VERSION: 1013
language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
script:
- rm -rf docker
- gradle -i clean build test
- mkdir docker && cp Dockerfile docker/ && cp build/libs/*.war docker/ && docker build -t opencadc/caom2-meta-ui:SNAPSHOT -t opencadc/caom2-meta-ui:alpine -t opencadc/caom2-meta-ui:${VERSION} -f docker/Dockerfile docker/
- cd integrationTest
- docker-compose up -d
- docker ps -a
- gradle -i -b ../build.gradle -Dca.nrc.cadc.reg.client.RegistryClient.host=$REGISTRY_HOST clean intTest
- cd ../ && rm -rf docker
after_success:
- if [ "$(. ./can-deploy.sh)" = "DEPLOY" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push opencadc/caom2-meta-ui:alpine; docker push opencadc/caom2-meta-ui:${VERSION}; fi
- if [ "$(. ./can-deploy.sh)" != "DEPLOY" ]; then echo "Not deploying."; fi
addons:
  hosts: proxy.cadc.dao.nrc.ca
notifications:
  slack:
    secure: d3jO70JUI6UqNJrPuafkteYJkLZv04mMVCJryi4lgdY4tFo2UkyAEZVP9vpk4uk6RHVQw+og6ZNp3lIMa8UP03IMY2dpm6YqDzHZxt9C5N4SKFHg5kbLKgsxvzYSb7xEY7KlfXZHL4+c9q/IEYu77Nftdv8IzLYuZnXRGjjp3sUw+azxwsx7mn/+HaGN6tdqUePN9l/wC4ezSW3WkOkezsGR1RKcMUMcXg1KnM7sBPa7Qv8Y14F6alcDuKQSLYq+NzG1cq5yW+S8VGvlsRnKpx4qH6GlDLNqUUJRqYOrREuvAiIQsy+TURHRQElHRy4bwv1MZAtQByR+Uk9aWdlX5u2V7pCyhjqdJ80t4dVickzQ4pLODiMlmJIeWhHZIYgFvrKh4Q9Pn8WDa10Kqu0ngffjmZTe1pw8O6W3RS8M/9i5kMWTv0jKKwtUw4VWzqB4VPFt6KM5vCsCr1F6LS32kFhnqtGi1Z8efhUB2brDPw4XVEglKnEJK6RBc9dLMVkeJ+CyJ7rnOtgl7YldJaa/gJOXfKjTmYS/bs33oHFocUj97PjlQH8txhF4jQs74K1cQj3LuL7Cm7mrW/1a1pbM/0sJ1BZLVq7qaHZ3j6Yb8PEApraWdayA4TODXvF2UspEDqT4mMgNs97S4g8TqC5JPa3llXgN7OMLK3erdvdJsb0=
