name: Java+Docker CI

on: 
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: build, test, and install caom2-search-lib
      run: cd caom2-search-lib && ../gradlew --info clean build test publishToMavenLocal

    - name: build, test, and install caom2-search-server
      run: cd caom2-search-server && ../gradlew --info clean build test publishToMavenLocal

    - name: build, test, and install caom2-ui-server
      run: cd caom2-ui-server && ../gradlew --info clean build test publishToMavenLocal

    - name: build, test caom2-meta-ui
      run: cd caom2-meta-ui && ../gradlew --info clean build test
